* Ma configuration ZMK pour Ferris Sweep

Ceci est un dépôt pour une configuration de clavier Ferris Sweep.

Buts :

- pour taper en français et en anglais
- pour une utilisation quotidienne d’[[https://www.gnu.org/s/emacs/][Emacs]] et de la console
- pour un clavier [[https://github.com/davidphilipbarr/Sweep][Ferris Sweep]]
- avec un micro-contrôleur compatible avec [[https://nicekeyboards.com/nice-nano/][nice!nano]] 2
- pour utiliser la disposition [[https://ergol.org/][Ergo-L]]
- en s’inspirant d’[[https://github.com/OneDeadKey/arsenik][Arsenik]]

* Détails

** Modificateurs sur les touches de repos

Pour une introduction au sujet, voici un article de référence : https://precondition.github.io/home-row-mods

Dans cette configuration, voici les correspondances de doigts utilisés :
- les _auriculaires_ pour la touche *méta*
- les _annulaires_ pour la touche *alt*
- les _majeurs_ pour la touche *majuscule*
- les _index_ pour la touche *contrôle*
** Calques

Voici les calques ou layers définis dans cette configuration

*** Par défaut

Le calque par défaut (~Default~) est standard pour les lettres.

Au niveau des pouces, de gauche à droite :
- à gauche, ~espace~ puis ~retour charriot~
- à droite, ~tab~ puis ~entrée~ (qui devient ~AltGr~ quand maintenu)

*** Chiffres

Ce calque (définition ~NUM~ ou nommé ~num_layer~) est activé par appui maintenu sur la touche droite du pouce gauche.

Sur la ligne de repos, les nombres de 1 à 10. La ligne du bas, les touches de fonction.

Sur la droite de la ligne du haut, les deux touches de fonction ~F11~ et ~F12~ qui ne tiennent pas sur la rangée du milieu.

*** Système et navigation

Ce calque (définition ~SYS~ ou nommé ~navsys_layer~) est activé par appui maintenu sur la touche gauche du pouce droit.

On retrouve la gestion du Bluetooth, le volume, les flèches, la pagination, l’échappement, égal/plus et d’autres fonctions propres à ZMK.
